---

#
# First setup a package_cache, especially when using
# your laptop and Vagrant
#

- hosts: package_cache
  roles:
  - package_cache

- hosts: 
  - all
  roles:
  - common

- hosts:
  - proxy
  - storage
  roles:
    - swift_common

- hosts: authentication
  roles:
   - authentication

- hosts: 
  - proxy
  roles:
  - proxy

#
# I would have expected serial to work here, and
# to be the right way to do it but at the time I
# tried recieved "too many files open" errors.
#

- hosts: storage
  #serial: 1
  roles:
  - storage

#
# These are not so much roles as starting services
# though also includes distributing the ring files.
# 

- hosts: proxy
  tasks:
  - include: start_proxy.yml

- hosts: storage
  tasks:
  - include: start_storage.yml
  