---

- name: tell memcached what IP to listen on
  lineinfile: dest=/etc/sysconfig/memcached regexp="^OPTIONS" line='OPTIONS="-l {{ ansible_enp0s10.ipv4.address }}"'  # Figure out actual IP
  notify: 
  - restart memcached 